### ISSUE TITLE
DTMF, Blind transfer and Attended Transfer

### ISSUE THREAD

**Issue by newlflextv** [vanbui1995/react-sipjs#16]
Dear, 

Can tell how to utilize DTMF, blind and attended transfer, if you add this will great helpful

**Comment by vanbui1995** [comment]
@newlflextv 
with DTMF, you can use archive that by use session.info https://sipjs.com/guides/send-dtmf/

in my example
```
CallSessionItem.tsx


const { session } = useSessionCall();
const dtmfOptions = {
  requestOptions: {
    body: {
      contentDisposition: "render",
      contentType: "application/dtmf-relay",
      content: "Signal=1\r\nDuration=1000"
    }
  }
};
session.info(dtmfOptions)

```

**Comment by vanbui1995** [comment]
bind and attended transfer is feature of IP PBX server, so the package can't support it @newlflextv, sip client only do the `refer` in this workflow, but note that its just a part of the workflow, other things need to be configured on IP PBX server

you totally follow the DTMF for refer method

```

session.refer('sip:userC@example.com')

```

**Comment by newlflextv** [comment]
Thanks for the support will test the DTMF and update 

can you please provide the example code 

> bind and attended transfer is feature of IP PBX server, so the package can't support it @newlflextv, sip client only do the `refer` in this workflow, but note that its just a part of the workflow, other things need to be configured on IP PBX server
> 
> you totally follow the DTMF for refer method
> 
> ```
> 
> session.refer('sip:userC@example.com')
> ```

understood already we have configured the transfer functionality in configured in pbx end. just want refer :
can you give example code  as per CallSessionItem.tsx

**Comment by vanbui1995** [comment]
@newlflextv you can see the CallSessionItem.tsx in the example folder: https://github.com/vanbui1995/react-sipjs/blob/870fcf0b44855a9726529b741db35d4e22936fb6/examples/full-example/src/CallSessionItem.tsx#L16

**Comment by newlflextv** [comment]
check and DTMF is working as expected thanks
