### ISSUE TITLE
stun having issue

### ISSUE THREAD

**Issue by newlflextv** [vanbui1995/react-sipjs#18]
Hi we have update the stun in you example for testing server not recognize 

import { SIPProvider } from "react-sipjs";
import { CallCenter } from "./CallCenter";

function App() {
  return (
    <div className="p-5">
      <SIPProvider
        options={{
          domain: "voice.greenewoos.in", // Your SIP domain
          webSocketServer: "wss://voice.greenewoos.in:8088", // WebSocket server URL
        }}
        mergedSessionManagerOptions={{
          userAgentOptions: {
            sessionDescriptionHandlerFactoryOptions: {
              peerConnectionConfiguration: {
                iceServers: [
                  { urls: "stun:stun.l.google.com:19302" }, // Google STUN server
                  // Optional TURN server:
                  // { 
                  //   urls: "turn:your_turn_server_address:3478", 
                  //   username: "your_turn_username", 
                  //   credential: "your_turn_password"
                  // }
                ],
              },
            },
          },
        }}
      >
        <div>
          <CallCenter />
        </div>
      </SIPProvider>
    </div>
  );
}

export default App;

**Comment by vanbui1995** [comment]
i see you commented the username, credential, if you decided override, you need override the whole object

**Comment by newlflextv** [comment]
we are using only google stun server for testing  not turn server that's why commented >. can you give us the example to implement in your example script

**Comment by vanbui1995** [comment]
you can follow the code in https://github.com/vanbui1995/react-sipjs/issues/17
