### ISSUE TITLE
Properties in useSessionCall cause build error

### ISSUE THREAD

**Issue by enesr** [vanbui1995/react-sipjs#19]
Hi,

Looks like an error popped up in your latest release (0.0.6) with SIPProviderContext properties. When you build the project all the properties of `useSessionCall` object in `SIPProviderContext.ts` get this error on `CallSessionItem.tsx` and project fails to build:
`src/CallSessionItem.tsx:9:5 - error TS2339: Property 'isHeld' does not exist on type`

Thanks

Enes

**Comment by vanbui1995** [comment]
hi @enesr , sorry for this, as you can see in newest version useSessionCall result is nullable, so just make sure the hook's result is not null first

<img width="592" alt="Screenshot 2024-11-29 at 19 50 59" src="https://github.com/user-attachments/assets/c7599856-ee9f-463e-8a8f-f0f60f0f9ed4">

**Comment by vanbui1995** [comment]
Updated example via this PR: https://github.com/vanbui1995/react-sipjs/pull/21
