### ISSUE TITLE
Auto Answer 

### ISSUE THREAD

**Issue by newlflextv** [vanbui1995/react-sipjs#20]
Can you guide to enable auto answer 

we have below config let us know which will support 

exten => 100,1,SIPAddHeader(Call-Info:<sip:>\;answer-after=0)
exten => 100,n,Dial(PJSIP/200)

exten => 100,1,SetVar(_ALERT_INFO=info=alert-autoanswer)
exten => 100,n,Dial(PJSIP/200)

exten => 100,1,Set(__SIPADDHEADER=Alert-Info: \;info=alert-autoanswer)
exten => 100,n,Dial(PJSIP/200)

**Comment by vanbui1995** [comment]
hi @newlflextv not sure what you want but auto answer in sip.js in my package, you can follow the code changes like this
<img width="736" alt="Screenshot 2024-11-29 at 20 37 15" src="https://github.com/user-attachments/assets/8111ee71-3ad2-4362-8258-08d7bf3e37d7">

CallCenter.tsx 
`examples/full-example/src/CallCenter.tsx`

**Comment by newlflextv** [comment]
Thanks dear its working
