### ISSUE TITLE
Delay in RTP/Audio streams 

### ISSUE THREAD

**Issue by newlflextv** [vanbui1995/react-sipjs#23]
Can you advise while making and receiving the call  the call establish taking 4 to 5 sec once attended the call its taking another 5 to 6 sec to established the audio on both end

we don't have any firewall rule 
No policy blockage 
all the ports are opened including RTP

is there anyway once call attended immediately here the audio

**Comment by vanbui1995** [comment]
seem i can't help your on this issue, the issue can be the server and connection, just mention again the package only wrap sip.js, and its not happen in the server and connection i tested
