### ISSUE TITLE
Ringtone on incoming & outgoing , popup window for answer and disconnect call 

### ISSUE THREAD

**Issue by newlflextv** [vanbui1995/react-sipjs#24]
Can you advise how to place the ringtone on both  incoming and outgoing 

Also advise how to place popup for incoming call with option (answer and disconnect) 
let say we have timeout for incoming call 60 sec, so once started receiving incoming call the popup should show  until 60 sec with the option Answer and  Disconnect 
If answer will connect the call 
If disconnect call will disconnect

**Comment by vanbui1995** [comment]
seem these buttons are shown in my example, you only need to adjust the logic by add your conditions  for the case you want 🤔

**Comment by newlflextv** [comment]
can you give the sample example

**Comment by vanbui1995** [comment]
> can you give the sample example
this folder: https://github.com/vanbui1995/react-sipjs/tree/main/examples/full-example
