### ISSUE TITLE
[feature]: multi-window application

### ISSUE THREAD

**Issue by dberardo-com** [vanbui1995/react-sipjs#4]
based on this discussion: https://github.com/onsip/SIP.js/issues/1060#issuecomment-1808441446

would it be possible to allow the usage of one shared websocket through multiple windows so that the user can use multiple instances of the application on different screens without the need of registering in each one of them ? 

there seems to be an issue when users register twice with the same account, i think it is not possible to double-register, therefore having and shared websocket connection seems the only viable way

**Comment by vanbui1995** [comment]
> there seems to be an issue when users register twice with the same account,
not sure what you was getting, but actually we totally register twice with the same account, the newest one will take incoming call

**Comment by dberardo-com** [comment]
I guess what I was asking for here is whether sharing the same websocket connection between browser tabs is a possibility or double registration is a must
