### ISSUE TITLE
[bug]: call to sessionManager.disconnect() never returns

### ISSUE THREAD

**Issue by dberardo-com** [vanbui1995/react-sipjs#5]
i am not being able to disconnect the websocket session, the call to await sessionManager.unregister()  resolves properly, while the one to await sessionManager.disconnect() never resolves.

is there any issue ?

**Comment by vanbui1995** [comment]
@dberardo-com Can you post the example code to somewhere for me can reproduce the issue?

**Comment by dberardo-com** [comment]
mm hard to say, does `await sessionManager.disconnect()` work for you ? or it hangs forever ?
