### ISSUE TITLE
Did somewone get video call work ?

### ISSUE THREAD

**Issue by giraudvalentin** [vanbui1995/react-sipjs#8]
Hi, I just test this lib, it work great for call but didn't see anything for videocall,
Has anyone managed to get them to work?

Thanks :)

**Comment by NeuralNemesis** [comment]
You would need to add constraints to the sessionDescriptionHandlerOptions from within the call( ) method as follows:

         await sessionManager?.call(
              `sip:${callTo}@domain.com`,
              {
                **sessionDescriptionHandlerOptions**: {
                    constraints: {
                      audio: true,
                      video: true
                    },
                  }
              }
            );

The call method has as arguments the following:
1. destination: string
2. inviterOptions?: **InviterOptions** | undefined
3. inviterInviteOptions?: InviterInviteOptions
and if you follow that up, you will find out that InviterOptions extends SessionOptions that has the following (these are also thing that you could add to the **call( )** method):
export interface InviterOptions extends SessionOptions {
    /** If true, an anonymous call. */
    anonymous?: boolean;
    /**
     * If true, the first answer to the local offer is immediately utilized for media.
     * Requires that the INVITE request MUST NOT fork.
     * Has no effect if `inviteWithoutSdp` is true.
     * Default is false.
     */
    earlyMedia?: boolean;
    /** Array of extra headers added to the INVITE. */
    extraHeaders?: Array<string>;
    /** If true, send INVITE without SDP. Default is false. */
    inviteWithoutSdp?: boolean;
    /** @deprecated TODO: provide alternative. */
    params?: {
        fromDisplayName?: string;
        fromTag?: string;
        fromUri?: string | URI;
        toDisplayName?: string;
        toUri?: string | URI;
    };
    /** @deprecated TODO: provide alternative. */
    renderbody?: string;
    /** @deprecated TODO: provide alternative. */
    rendertype?: string;
    /** Modifiers to pass to SessionDescriptionHandler during the initial INVITE transaction. */
    sessionDescriptionHandlerModifiers?: Array<SessionDescriptionHandlerModifier>;
    /** Options to pass to SessionDescriptionHandler during the initial INVITE transaction. */
    **sessionDescriptionHandlerOptions?: SessionDescriptionHandlerOptions;**
    /** Modifiers to pass to SessionDescriptionHandler during re-INVITE transactions. */
    sessionDescriptionHandlerModifiersReInvite?: Array<SessionDescriptionHandlerModifier>;
    /** Options to pass to SessionDescriptionHandler during re-INVITE transactions. */
    sessionDescriptionHandlerOptionsReInvite?: SessionDescriptionHandlerOptions;
}
and here the SessionDescriptionHandlerOptions has the following:
export interface SessionDescriptionHandlerOptions {
    **constraints?: object;**
}

See [https://github.com/onsip/SIP.js/blob/master/docs/README.md](url) for more info about **sipjs API**.

**Comment by steven-moneyforward** [comment]
hi @giraudvalentin i have just released a new version, you can archive your goal via mergedSessionManagerOptions

code example: follow https://sipjs.com/guides/simple/
```
function App() {

  const refRemoteVideo = useRef<HTMLVideoElement>(null);
  const refLocalVideo = useRef<HTMLVideoElement>(null);
  
  return (
    <div className="p-5">

       <video ref={refRemoteVideo} id="remoteVideo"></video>
       <video ref={refLocalVideo} id="localVideo" muted={true}></video>

      <SIPProvider
        options={{
          domain: "voice.chatchilladev.sip.jambonz.cloud",
          webSocketServer: "wss://sip.jambonz.cloud:8443",
        }}
        mergedSessionManagerOptions={{
          media: {
            constraints: {
              audio: true,
              video: true,
            },
            local: {
              video: refLocalVideo.current as HTMLVideoElement
            },
            remote: {
              video: refRemoteVideo.current as HTMLVideoElement,
              audio: refRemoteVideo.current as HTMLVideoElement
            }
          }
        }}
      >
        <div>
          <CallCenter />
        </div>
      </SIPProvider>
    </div>
  );
}
```
