### ISSUE TITLE
Can't dail to a phone number

### ISSUE THREAD

**Issue by greatapps** [vanbui1995/react-sipjs#9]
I am not able to pass a phone number to call :

await sessionManager?.call(`sip:${callTo}@voice.chatchilladev.sip.jambonz.cloud`);

**Comment by vanbui1995** [comment]
hi @greatapps this is example URL i use jambonz on the server side, you should have your own one, you may need to configure sip forward to real phone number, but that's not context of this package, your system should work on standard sip client application first for example: https://apps.apple.com/us/app/telephone/id406825478?mt=12, this package only help you build your own client app in your web app (copy feature from example app to your web app)

so this app have no responsibility to build the SIP system
